apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tweetapp-pepoc-test2
  namespace: development
spec:
  project: default
  source:
    repoURL: https://github.com/engbalaji/tweetapp-pepoc-test2.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}